# yaml-language-server: $schema=https://raw.githubusercontent.com/DavidAnson/markdownlint-cli2/refs/heads/main/schema/markdownlint-cli2-config-schema.json

config:
  default: true

  line-length:
    line_length: 120
    heading_line_length: 120
    code_block_line_length: 120

  list-marker-space: false

ignores:
  - CHANGELOG.md
