# yaml-language-server: $schema=https://raw.githubusercontent.com/DavidAnson/markdownlint/v0.34.0/schema/markdownlint-config-schema.json

default: true

line-length:
  line_length: 120
  heading_line_length: 120
  code_block_line_length: 120

list-marker-space: false
