#!/usr/bin/env bash

set -euo pipefail

INSTALL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SETUP_DIR="${INSTALL_DIR}/setup"

. "${SETUP_DIR}/printing.sh"

. "${SETUP_DIR}/prerequisites.sh"
. "${SETUP_DIR}/defaults.sh"
. "${SETUP_DIR}/brews.sh"
. "${SETUP_DIR}/stow.sh"
. "${SETUP_DIR}/shell.sh"
. "${SETUP_DIR}/bar.sh"

# start sketchybar and border services
brew services start sketchybar
brew services start borders

# open aerospace
open -a "Aerospace"

# restart sketchybar in case things have changed between updates
sketchybar --reload

# run neofetch
neofetch
