#!/usr/bin/env bash

set -euo pipefail

brew services stop borders 2>/dev/null || true
brew services stop sketchybark 2>/dev/null || true

INSTALL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SETUP_DIR="${INSTALL_DIR}/setup"

. "${SETUP_DIR}/printing.sh"

. "${SETUP_DIR}/prerequisites.sh"
. "${SETUP_DIR}/defaults.sh"
. "${SETUP_DIR}/brews.sh"
. "${SETUP_DIR}/stow.sh"
. "${SETUP_DIR}/shell.sh"

# run neofetch
neofetch
