#!/usr/bin/env sh

set -eu

default_color=$(tput sgr 0)

yellow="$(tput setaf 3)"
warn() {
	printf "%s==> %s%s\n" "$yellow" "$1" "$default_color"
}

red="$(tput setaf 1)"
error() {
	printf "%s==> %s%s\n" "$red" "$1" "$default_color"
}

LAUNCH_DAEMONS=/Library/LaunchDaemons/

ZSCALER_SERVICE="${LAUNCH_DAEMONS}/com.zscaler.service.plist"
ZSCALER_TUNNEL="${LAUNCH_DAEMONS}/com.zscaler.tunnel.plist"

started=

if [ -f "${ZSCALER_SERVICE}" ] && ! sudo launchctl list | grep 'com.zscaler.service' > /dev/null; then
	warn "enabling zscaler service..."
	sudo launchctl load "${ZSCALER_SERVICE}"
	started=1
fi

if [ -f "${ZSCALER_TUNNEL}" ] && ! sudo launchctl list | grep 'com.zscaler.tunnel' > /dev/null; then
	warn "enabling zscaler tunnel..."
	sudo launchctl load "${ZSCALER_TUNNEL}"
	started=1
fi

if [ -n "${started:-}" ]; then
	warn "waiting for tunnel..."
	sleep 10
fi
