#!/usr/bin/env sh

set -eu

default_color=$(tput sgr 0)
yellow="$(tput setaf 3)"
green="$(tput setaf 2)"
blue="$(tput setaf 4)"

info() {
	printf "%s==> %s%s\n" "$blue" "$1" "$default_color"
}

success() {
	printf "%s==> %s%s\n" "$green" "$1" "$default_color"
}

warning() {
	printf "%s==> %s%s\n" "$yellow" "$1" "$default_color"
}

info "setting up ssh agent..."

if ! ssh-add -L 1> /dev/null 2>&1; then
	warning "adding resident keys from security key to agent..."
	ssh-add -K
	success "keys successfully added to agent!"
fi

info "updating git allowed signers..."

allowed_signers="${HOME}/.ssh/.git_allowed_signers"
user=$(git config --get user.email)
key=$(git-sk)

if [ -z "${user:-}" ]; then
	error "user email is not set"
	exit 1
fi

if [ -z "${key:-}" ]; then
	error "user signing key is not set"
	exit 1
fi

public_key="${key#key::}"

touch "${allowed_signers}"
if echo "${public_key}" | grep -F -q "${public_key}" 1> /dev/null 2>&1; then
	warning "signing key already exists in allowed signers file"
	exit 1
fi

info "adding ${user}: ${public_key} to ${allowed_signers}"
echo "${user} namespaces=\"git\" ${public_key}" >> "${allowed_signers}"
