#!/usr/bin/env sh

set -eu

default_color=$(tput sgr 0)

blue="$(tput setaf 4)"
info() {
	printf "%s==> %s%s\n" "$blue" "$1" "$default_color"
}

green="$(tput setaf 2)"
success() {
	printf "%s==> %s%s\n" "$green" "$1" "$default_color"
}

yellow="$(tput setaf 3)"
warn() {
	printf "%s==> %s%s\n" "$yellow" "$1" "$default_color"
}

info "setting up ssh agent..."

if ! ssh-add -L 1> /dev/null 2>&1; then
	warn "adding resident keys from security key to agent..."
	ssh-add -K
	success "keys successfully added to agent!"
fi

info "updating git allowed signers..."
email=$(git config --get user.email)
allowed_signers="${XDG_CONFIG_HOME}/private/git/allowed_signers"
key=$(git-github-sk 2> /dev/null || git-forgejo-sk 2> /dev/null)

if [ -z "${email:-}" ]; then
	error "user email is not set"
	exit 1
fi

if [ -z "${key:-}" ]; then
	error "user signing key is not set"
	exit 1
fi

public_key="${key#key::}"

mkdir -p "$(dirname "${allowed_signers}")"
touch "${allowed_signers}"

signer_line="${email} namespaces=\"git\" ${public_key}"

if grep -qxF "${signer_line}" "${allowed_signers}"; then
	info "${email}: ${public_key} already present in ${allowed_signers}"
else
	info "adding ${email}: ${public_key} to ${allowed_signers}"
	echo "${signer_line}" >> "${allowed_signers}"
fi
