#!/usr/bin/env bash

set -euo pipefail

default_color=$(tput sgr 0)

blue="$(tput setaf 4)"
info() {
	printf "%s==> %s%s\n" "$blue" "$1" "$default_color"
}

green="$(tput setaf 2)"
success() {
	printf "%s==> %s%s\n" "$green" "$1" "$default_color"
}

yellow="$(tput setaf 3)"
warn() {
	printf "%s==> %s%s\n" "$yellow" "$1" "$default_color"
}

info "checking github auth..."

function join_by {
	local d=${1-} f=${2-}
	if shift 2; then
		printf %s "$f" "${@/#/$d}"
	fi
}

account="${1:-}"
required_scopes=('gist' 'notifications' 'project' 'repo' 'user' 'workflow' 'read:org' 'read:public_key' 'read:ssh_signing_key' 'write:ssh_signing_key')

if [ -z "${account:-}" ]; then
	account=$(
		{
			command gh auth status --json 'hosts' --jq '.hosts."github.com".[].login' 2> /dev/null || true
			printf 'new account\n'
		} |
			fzf --header='select github account' --select-1
	)

	if [ "${account}" = "new account" ]; then
		gh auth login \
			--git-protocol https \
			--hostname github.com \
			--scopes "$(join_by ',' "${required_scopes[@]}")" \
			--web \
			--clipboard

		exit 0
	fi

	command gh auth switch --user "${account}"
fi

if ! command gh auth status --json 'hosts' --jq ".hosts.\"github.com\".[] | select(.login == \"${account}\") | .active" 1> /dev/null 2>&1; then
	warn "not logged into github, will login now..."
	gh auth login \
		--git-protocol https \
		--hostname github.com \
		--scopes "$(join_by ',' "${required_scopes[@]}")" \
		--web \
		--clipboard

	exit 0
fi

active=$(command gh auth status --active --json hosts --jq '.hosts["github.com"][0].login' 2> /dev/null)

if [ "${account:-}" != "${active:-}" ]; then
	command gh auth switch --user "${account:-}" 1> /dev/null 2>&1
fi

scopes=$(command gh auth status --active --json 'hosts' --jq '.hosts."github.com".[] | .scopes' 2> /dev/null)

for scope in "${required_scopes[@]}"; do
	if ! echo "${scopes:-}" | grep -F -q "${scope}" 1> /dev/null 2>&1; then
		warn "not logged into github with the required scopes..."
		command gh auth refresh \
			--hostname github.com \
			--scopes "$(join_by ',' "${required_scopes[@]}")" \
			--clipboard
		break
	fi
done

success "logged into github with the required scopes"
