#!/usr/bin/env sh

set -eu

allowed_keys=$(fj user key list --verbose | awk '/^[[:space:]]+(sk-ssh-)/ {print $2}')

if [ -z "${allowed_keys:-}" ]; then
	echo "No signing keys are available for the currently authenticated user." >&2
	exit 1
fi

available_keys=$(ssh-add -L 2> /dev/null)

if [ -z "${available_keys:-}" ]; then
	ssh-add -K < /dev/null
	available_keys=$(ssh-add -L 2> /dev/null)
fi

if [ -z "${available_keys:-}" ]; then
	echo "No keys found in local ssh agent." >&2
	exit 1
fi

match_key=$(echo "$available_keys" | while IFS= read -r line; do
	key_blob=$(echo "${line}" | cut -d ' ' -f 2)

	if echo "${allowed_keys}" | grep -F -q "${key_blob}"; then
		echo "${line}"
		break
	fi
done)

if [ -z "${match_key:-}" ]; then
	echo "No local agent key matches the allowed signing keys." >&2
	exit 1
fi

echo "key::${match_key}"
