#!/usr/bin/env sh

set -eu

REPOS_DIR="${REPOS_DIR:-${HOME}/Repos}"
selected="${1:-}"

if [ ! -d "${REPOS_DIR:-}" ]; then
	REPOS_DIR='.'
fi

if [ "${selected:-}" = "." ]; then
	REPOS_DIR="${PWD}"
	selected=
fi

selected=$(find "${REPOS_DIR}" -type d -mindepth 0 -maxdepth 4 -exec test -d {}/.git \; -print -prune | fzf --query "${selected}" --exit-0 --select-1)

if [ -z "${selected:-}" ]; then
	exit 0
fi

name=$(basename "${selected}" | tr . _)
printf '\033]0;%s\007' "${name}" || true

if ! tmux has-session -t "${name}" 2> /dev/null; then
	tmux -u new-session -d -s "${name}" -n ' nvim' -c "${selected}" -x - -y - "${EDITOR}" . \; \
		split-window -v -l '10%' -c "${selected}" \; \
		select-pane -t 1 \; \
		new-window -a -d -c "${selected}" -n '󰯉 claude (agent)' claude \; \
		new-window -a -d -c "${selected}"
fi

tmux -u attach-session -t "${name}" -c "${selected}"
