#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 3

[palette]
bg = '#16181a'
fg = '#ffffff'

rosewater = '#ff5ea0'
flamingo = '#ff5ea0'
pink = '#ff5ea0'
mauve = '#ff5ef1'
red = '#ff6e5e'
maroon = '#ffbd5e'
peach = '#ffbd5e'
yellow = '#f1ff5e'
green = '#5eff6c'
teal = '#5ef1ff'
sky = '#5ef1ff'
sapphire = '#5ef1ff'
blue = '#5ea1ff'
lavender = '#bd5eff'

subtext_1 = '#7b8496'
subtext_0 = '#7b8496'
overlay_2 = '#3c4048'
overlay_1 = '#3c4048'
overlay_0 = '#3c4048'
surface_2 = '#1e2124'
surface_1 = '#1e2124'
surface_0 = '#1e2124'
mantle = '#1e2124'
crust = '#1e2124'

# Colors
# Surfaces and overlays
[[blocks]]
type = 'prompt'
alignment = 'left'

[[blocks.segments]]
type = 'shell'
style = 'diamond'
leading_diamond = '╭─'
template = ' {{ .Name }} '
background = 'p:blue'
foreground = 'p:fg'
Text = ''
Duration = 0
NameLength = 0

[[blocks.segments]]
type = 'root'
style = 'diamond'
template = '<parentBackground></>  '
background = 'p:red'
foreground = 'p:yellow'
Text = ''
Duration = 0
NameLength = 0

[[blocks.segments]]
type = 'path'
style = 'powerline'
powerline_symbol = ''
template = '  {{ .Path }} '
background = 'p:peach'
foreground = 'p:crust'
Text = ''
Duration = 0
NameLength = 0

[blocks.segments.properties]
folder_icon = '  '
home_icon = ''
style = 'folder'

[[blocks.segments]]
type = 'git'
style = 'powerline'
powerline_symbol = ''
background_templates = [
    '{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}',
    '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:green{{ end }}',
    '{{ if gt .Ahead 0 }}p:lavender{{ end }}',
    '{{ if gt .Behind 0 }}p:lavender{{ end }}',
]
template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}<p:red>  {{ .Staging.String }}</>{{ end }} '
background = 'p:yellow'
foreground = 'p:crust'
Text = ''
Duration = 0
NameLength = 0

[blocks.segments.properties]
branch_icon = ' '
fetch_status = true
fetch_upstream_icon = true

[[blocks.segments]]
type = 'executiontime'
style = 'diamond'
trailing_diamond = ''
template = '  {{ .FormattedMs }}⠀'
background = 'p:crust'
foreground = 'p:fg'
Text = ''
Duration = 0
NameLength = 0

[blocks.segments.properties]
style = 'roundrock'
threshold = 0.0

[[blocks]]
type = 'prompt'
alignment = 'right'

[[blocks.segments]]
type = 'node'
style = 'diamond'
leading_diamond = ''
trailing_diamond = ' '
template = ' {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}'
background = '#303030'
foreground = '#3C873A'
Text = ''
Duration = 0
NameLength = 0

[blocks.segments.properties]
fetch_package_manager = true
npm_icon = ' <#cc3a3a></> '
yarn_icon = ' <#348cba></>'

[[blocks.segments]]
type = 'python'
style = 'diamond'
leading_diamond = ''
trailing_diamond = ' '
template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}'
background = '#306998'
foreground = '#FFE873'
Text = ''
Duration = 0
NameLength = 0

[[blocks.segments]]
type = 'java'
style = 'diamond'
leading_diamond = ''
trailing_diamond = ' '
template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
background = '#0e8ac8'
foreground = 'p:fg'
Text = ''
Duration = 0
NameLength = 0

[[blocks.segments]]
type = 'dotnet'
style = 'diamond'
leading_diamond = ''
trailing_diamond = ' '
template = ' {{ if .Unsupported }}{{ else }}{{ .Full }}{{ end }}'
background = '#0e0e0e'
foreground = '#0d6da8'
Text = ''
Duration = 0
NameLength = 0

[[blocks.segments]]
type = 'go'
style = 'diamond'
leading_diamond = ''
trailing_diamond = ' '
template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
background = 'p:fg'
foreground = '#06aad5'
Text = ''
Duration = 0
NameLength = 0

[[blocks.segments]]
type = 'rust'
style = 'diamond'
leading_diamond = ''
trailing_diamond = ' '
template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
background = '#f3f0ec'
foreground = '#925837'
Text = ''
Duration = 0
NameLength = 0

[[blocks.segments]]
type = 'dart'
style = 'diamond'
leading_diamond = ' '
trailing_diamond = ' '
template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
background = '#e1e8e9'
foreground = '#055b9c'
Text = ''
Duration = 0
NameLength = 0

[[blocks.segments]]
type = 'angular'
style = 'diamond'
leading_diamond = ' '
trailing_diamond = ' '
template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
background = 'p:fg'
foreground = '#ce092f'
Text = ''
Duration = 0
NameLength = 0

[[blocks.segments]]
type = 'nx'
style = 'diamond'
leading_diamond = ' '
trailing_diamond = ' '
template = '{{ if .Error }}{{ .Error }}{{ else }}Nx {{ .Full }}{{ end }}'
background = '#1e293b'
foreground = 'p:fg'
Text = ''
Duration = 0
NameLength = 0

[[blocks.segments]]
type = 'julia'
style = 'diamond'
leading_diamond = ' '
trailing_diamond = ' '
template = '<#ca3c34></> {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
background = '#945bb3'
foreground = '#359a25'
Text = ''
Duration = 0
NameLength = 0

[[blocks.segments]]
type = 'ruby'
style = 'diamond'
leading_diamond = ''
trailing_diamond = ' '
template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
background = 'p:fg'
foreground = '#9c1006'
Text = ''
Duration = 0
NameLength = 0

[[blocks.segments]]
type = 'azfunc'
style = 'diamond'
leading_diamond = ''
trailing_diamond = ' '
template = '<#f5bf45></> {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
background = 'p:fg'
foreground = '#5398c2'
Text = ''
Duration = 0
NameLength = 0

[[blocks.segments]]
type = 'aws'
style = 'diamond'
leading_diamond = ''
trailing_diamond = ' '
template = ' {{.Profile}}{{if .Region}}@{{.Region}}{{end}}'
background = '#565656'
foreground = '#faa029'
Text = ''
Duration = 0
NameLength = 0

[[blocks.segments]]
type = 'kubectl'
style = 'diamond'
leading_diamond = ''
trailing_diamond = ''
template = ' {{.Context}}{{if .Namespace}} :: {{.Namespace}}{{end}}'
background = '#316ce4'
foreground = 'p:fg'
Text = ''
Duration = 0
NameLength = 0

[[blocks.segments]]
type = 'os'
style = 'diamond'
leading_diamond = ''
trailing_diamond = '<transparent,background></>'
template = ' {{ if .WSL }}WSL at {{ end }}{{.Icon}} '
background = 'p:overlay_0'
foreground = 'p:bg'
Text = ''
Duration = 0
NameLength = 0

[blocks.segments.properties]
linux = ''
macos = ''
windows = ''

[[blocks.segments]]
type = 'battery'
style = 'powerline'
powerline_symbol = ''
invert_powerline = true
background_templates = [
    '{{if eq "Charging" .State.String}}p:peach{{end}}',
    '{{if eq "Discharging" .State.String}}p:yellow{{end}}',
    '{{if eq "Full" .State.String}}p:green{{end}}',
]
template = ' {{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }}{{ .Error }} '
background = 'p:peach'
foreground = 'p:mantle'
Text = ''
Duration = 0
NameLength = 0

[blocks.segments.properties]
charged_icon = ' '
charging_icon = ' '
discharging_icon = ' '

[[blocks.segments]]
type = 'time'
style = 'diamond'
invert_powerline = true
leading_diamond = ''
trailing_diamond = ''
template = '  {{ .CurrentDate | date .Format }} '
background = 'p:blue'
foreground = 'p:fg'
Text = ''
Duration = 0
NameLength = 0

[blocks.segments.properties]
time_format = '_2,15:04'

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'text'
style = 'plain'
template = '╰─'
background = 'transparent'
foreground = 'p:teal'
Text = ''
Duration = 0
NameLength = 0

[[blocks.segments]]
type = 'status'
style = 'plain'
foreground_templates = ['{{ if gt .Code 0 }}p:red{{ end }}']
template = ' '
background = 'transparent'
foreground = 'p:fg'
Text = ''
Duration = 0
NameLength = 0

[blocks.segments.properties]
always_enabled = true
