#! /usr/bin/env sh

set -eu

LAUNCH_DAEMONS=/Library/LaunchDaemons/

ZSCALER_SERVICE="${LAUNCH_DAEMONS}/com.zscaler.service.plist"
ZSCALER_TUNNEL="${LAUNCH_DAEMONS}/com.zscaler.tunnel.plist"

if [ -f "${ZSCALER_SERVICE}" ] && ! sudo launchctl list | grep 'com.zscaler.service' >/dev/null; then
	sudo launchctl load "${ZSCALER_SERVICE}"
fi

if [ -f "${ZSCALER_TUNNEL}" ] && ! sudo launchctl list | grep 'com.zscaler.tunnel' >/dev/null; then
	sudo launchctl load "${ZSCALER_TUNNEL}"
fi
